# Generated by Django 6.0.3 on 2026-04-01 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('supplier', 'Fournisseur'), ('provider', 'Prestataire'), ('both', 'Les deux')], default='supplier', max_length=10)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('intervention_mode', models.CharField(choices=[('onsite', 'Sur site'), ('remote', 'À distance'), ('both', 'Les deux')], default='both', max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Fournisseur / Prestataire',
                'verbose_name_plural': 'Fournisseurs / Prestataires',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('desktop', 'Ordinateur de bureau'), ('laptop', 'Laptop'), ('printer', 'Imprimante'), ('scanner', 'Scanner'), ('server', 'Serveur'), ('network', 'Équipement réseau'), ('phone', 'Téléphone'), ('other', 'Autre')], max_length=20)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('active', 'En service'), ('broken', 'En panne'), ('repair', 'En réparation'), ('retired', 'Mis au rebut'), ('stock', 'En stock')], default='stock', max_length=10)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('site', models.CharField(choices=[('bobo', 'Bobo-Dioulasso'), ('ouaga', 'Ouagadougou')], default='bobo', max_length=10)),
                ('is_laptop', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='users.department')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='equipment.supplier')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('delivery_note', models.FileField(blank=True, null=True, upload_to='delivery_notes/')),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
                'ordering': ['-date_start'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('editor', models.CharField(blank=True, max_length=100)),
                ('license_key', models.CharField(blank=True, max_length=255)),
                ('total_licenses', models.PositiveIntegerField(default=1)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('equipment', models.ManyToManyField(blank=True, related_name='licenses', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Licence logicielle',
                'verbose_name_plural': 'Licences logicielles',
            },
        ),
    ]
