# Generated by Django 6.0.3 on 2026-04-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="lifespan_years",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="warranty_end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
