# Generated by Django 6.0.3 on 2026-04-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_ticket_archived_at_ticket_archived_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="intervention",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="intervention",
            name="materials_provided",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="intervention",
            name="purchase_order_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="ticket",
            name="observations",
            field=models.TextField(blank=True),
        ),
    ]
